version: '3'

volumes:
  jupyter_data: {}

services:
  jupyter:
    build:
      context: .
      dockerfile: ./compose/jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    depends_on:
      - jupyter
    networks:
      traefik:
        aliases:
          - bouyoucus_nginx
      default:
        aliases:
          - nginx
    ports:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.backend=bouyoucus_nginx
      - traefik.frontend.rule=Host:bouyoucus.mgabarda.com
      - traefik.docker.network=traefik
      - traefik.port=80
      - traefik.protocol=http

networks:
  traefik:
    external: true